// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlA0Pwsk0nJRzwqtrH1Bt9JnlxAhfiEIw',
    appId: '1:829907800848:web:b2007916283a889f88cb95',
    messagingSenderId: '829907800848',
    projectId: 'sureride-fbff8',
    authDomain: 'sureride-fbff8.firebaseapp.com',
    storageBucket: 'sureride-fbff8.firebasestorage.app',
    measurementId: 'G-4BG081DBT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDghbSJA5oCRtFWvVn1ZzIllOvCmw5StV0',
    appId: '1:829907800848:android:63f246f1ac55ab2a88cb95',
    messagingSenderId: '829907800848',
    projectId: 'sureride-fbff8',
    storageBucket: 'sureride-fbff8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzZbD9x6PGYB1tI9itJDocWfU3n4Dz4Ic',
    appId: '1:829907800848:ios:609a3c9cecde252088cb95',
    messagingSenderId: '829907800848',
    projectId: 'sureride-fbff8',
    storageBucket: 'sureride-fbff8.firebasestorage.app',
    iosBundleId: 'com.example.sureride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzZbD9x6PGYB1tI9itJDocWfU3n4Dz4Ic',
    appId: '1:829907800848:ios:609a3c9cecde252088cb95',
    messagingSenderId: '829907800848',
    projectId: 'sureride-fbff8',
    storageBucket: 'sureride-fbff8.firebasestorage.app',
    iosBundleId: 'com.example.sureride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlA0Pwsk0nJRzwqtrH1Bt9JnlxAhfiEIw',
    appId: '1:829907800848:web:20071a35739d8d4988cb95',
    messagingSenderId: '829907800848',
    projectId: 'sureride-fbff8',
    authDomain: 'sureride-fbff8.firebaseapp.com',
    storageBucket: 'sureride-fbff8.firebasestorage.app',
    measurementId: 'G-QWREVYYL2S',
  );
}
